### ISSUE TITLE
Prototype insertion of steam inventory items  into product table of an online marketplace component

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#168]
Create a cron job that queries all registered users inventory from steam and inserts or refreshes into their pertinent store inventory.  We are looking at two candidate components, sellacious and jmarket.  install both on local to test and determine best implementation approach.

**Comment by jasonGonzales33** [comment]
Update:

Cron jobs can be done using Fabrik Scheduled Tasks (tested)
Fabrik Scheduled Tasks scripts are at located at  /plugins/fabrik_cron/php/scripts/
plugin: System - Fabrik Scheduled Tasks, has to be enabled (this is disabled as default)

Steam item price is now included. It is in separate call. Schema is:
http://steamcommunity.com/market/priceoverview/?currency=1&appid=" . <APPID> . "&market_hash_name=" . <MARKET_HASH_NAME>

*Now awaiting support/forum to reply regarding my question on how I can import my array of data (the array from the steam calls)
to the items in Sellacious automated-wise since it gonna be done as cron

Also, was not able to try Jmarket as it is a paid download AFAIK

**Comment by ppantilla** [comment]
proceed with validating sellacious; we need to also know how to be able to customize the checkout functionality to accept cool.   This is 1 of the 2 deciding factors for deciding between the two.

**Comment by jasonGonzales33** [comment]
Prototype is done

sample products display: http://45.58.40.76/jason/index.php/steammarket

Now proceeding to enhancements - ticket 175

**Comment by laisee** [comment]
Looks pretty nice. How will it fit into the existing page structure?

**Comment by jasonGonzales33** [comment]
It will be displayed on the products display module
