### ISSUE TITLE
Add to Cart button

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#184]
needs to add the selected item to the shopping cart.  also, colors need to be changed to match the template

**Comment by jasonGonzales33** [comment]
The items are added correctly to the corresponding user that added the item to their cart. This is verified by going through the database. Furthermore, the menu item is displaying the correct items. The issue is with the module. The module does not really displaying anything useful (literally it just says Please Wait). I may need to consult the forums/support for this one.

**Comment by ppantilla** [comment]
try switching the template to gantry 5 and see if it behaves differently and also open up a support ticket
