### ISSUE TITLE
CM Feedback on PPT - Marketing Plan

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#27]
Develop marketing plan based around use of relevant media for target audience

**Comment by chrismaden** [comment]
Suggestions...

1. Some kind of member-get-member scheme (if it's not already in there). As I understand it, tokens are tradeable commodities, so reward members who get other members by giving them tokens. 

2. Design the inventive scheme so that existing members are rewarded on an on-going basis for recruiting ACTIVE new members - i.e., if Peter recruits Sue and Sue logs on and never again uses the system, Peter gets only a single token, but if Sue uses the system lots, Peter gets the occasional bonus token.

3. Consider using a pyramid approach, so if Peter recruits Sue and Sue recruits Edgar, Stefan and Raju, Peter gets a small cut of Sue's action for her recruitment of Edgar, Stefan and Raju.

**Comment by laisee** [comment]
1. Yes
2. Yes, some kind of activity metric to reward real ppl generating useful content
3. Hmmm. How close to pyramid should be go ...  Bed enough that bitcoin is agigantic ponzi already. ;-/

**Comment by laisee** [comment]
Add a spreadsheet showing the distribution of COOL tokens.

**Comment by laisee** [comment]
engaged social media marketing on fiverr.com
1. 3 covers for twitter, facebook, instagranm
2. simple trial campaign with metrics

**Comment by laisee** [comment]
Plan sourced from fiverr.com. Creating new task to execute plan in 2 week sprints.
